### ISSUE TITLE
Tracking memory model abstraction violations

### ISSUE THREAD

**Issue by travitch** [GaloisInc/pate#175]
There are a number of places in the verifier that violate what should be abstraction boundaries in the memory model. These significantly complicate any progress on improving the memory model (either for performance or soundness). This issue is intended to track the violations we identify, determine what semantics are required to support them, and transform them into structured APIs presented by the memory model for consumption in the rest of the verifier. Some of these are taken from #97 (reported by @dmwit)

- [ ] `bindMemory` in Pate.Verification.Domain
- [ ] `flatVarBinds` in Pate.SimState
- [ ] `memPredPre` in Pate.Equivalence
- [ ] `guessMemoryDomain` in Pate.Verification.Domain (caller of `bindMemory`)
- [ ] `groundBV` in Pate.Proof.Ground (calls `getPointerTags`, which traverses formulas to find undefined pointer operations)

Around several of these, there are additional direct accesses to the `memArr` of the memory model implementation. All of these need to be eliminated and abstracted into a structured interface to keep the memory model abstract.

**Comment by travitch** [comment]
Looking at `Pate.Discovery.exactEquivalence`, this one seems easy enough to understand. The intended operation is that we need a `WI.Pred sym` that indicates whether or not two memory post states are equivalent.

```
equivalentMemory :: sym -> MemImpl sym -> MemImpl sym -> Pred sym
```

**Comment by travitch** [comment]
For `Pate.SimState.flatVarBinds`, I'm not quite sure what is going on. The names imply that it wants to make a binding from a variable to the array in the memory model. The variable comes from `MemTraceVar` wrapper that is allocated in the memory model. Looking at that allocation site (`initMemTraceVar`), it looks like the variable is actually the initial array (before any memory operations are performed on it).

Ultimately, all of that gets used in `bindSpec`, which does a lot of variable rebinding in ways I don't understand. Tracing out the source of that variable makes it very unclear to me what is intended here.
