### ISSUE TITLE
Review and update user-manual

### ISSUE THREAD

**Issue by thebendavis** [GaloisInc/pate#395]
- [x] add SBIR info (as was added to the README in #404)
- [x] blocked on #401 => update description of use of colors and add screenshot of Binary Ninja UI
- [ ] point to or add a standalone target to use as a running example: ideally the target added in #417
